### ISSUE TITLE
graph bug fix

### ISSUE THREAD

**Issue by MASHOD0** [MASHOD0/Plagarism_checker_application#10]
display the labels clearly on the graph generated in the results 
modify `results.html` any additional css files created should be stored in `static/`

**Comment by SaiSantosh2209** [comment]
Hey @MASHOD0  I would like to work on this issue please rate my PR

**Comment by MASHOD0** [comment]
Hi @SaiSantosh2209 I have reviewed and merged your pull request it looked really good, looking forward for more collaborations
